name: Run CLI test

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

env:
  PYTHON_VERSION: 3.11

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install parquet-tools
        run: |
          python -m pip install .
      - name: Run test[help]
        run: |
          parquet-tools --help
          parquet-tools show --help
          parquet-tools csv --help
          parquet-tools inspect --help
      - name: Run show
        run: |
          parquet-tools show ./tests/test1.parquet
          parquet-tools show ./tests/*
          parquet-tools show ./tests/test1.parquet ./tests/test2.parquet
          parquet-tools show --format github ./tests/test1.parquet
          parquet-tools show --head 10 ./tests/test1.parquet
          parquet-tools show --head 1 ./tests/test1.parquet
          parquet-tools show --columns one,three ./tests/test1.parquet
      - name: Run csv
        run: |
          parquet-tools csv ./tests/test1.parquet
          parquet-tools csv ./tests/*
          parquet-tools csv ./tests/test1.parquet ./tests/test2.parquet
          parquet-tools csv --head 10 ./tests/test1.parquet
          parquet-tools csv --head 1 ./tests/test1.parquet
          parquet-tools csv --columns one,three ./tests/test1.parquet
      - name: Run inspect
        run: |
          parquet-tools inspect ./tests/test1.parquet
          parquet-tools inspect --detail ./tests/test1.parquet
